- name: Install and configure nginx
  hosts: test
  become: yes
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: yes
        
    - name: Copy index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
